version: '3.8'
services:
  # kafka:
    # image: bitnami/kafka:latest
    # ports:
    #   - "9092:9092"
    #   - "9093:9093"
    # environment:
    #   KAFKA_ENABLE_KRAFT_MODE: "yes"
    #   KAFKA_CFG_NODE_ID: 1
    #   KAFKA_CFG_PROCESS_ROLES: broker,controller
    #   KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
    #   KAFKA_CFG_LISTENERS: PLAINTEXT_BROKER://:9092,CONTROLLER://:9093
    #   KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT_BROKER://localhost:9092
    #   KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT_BROKER:PLAINTEXT,CONTROLLER:PLAINTEXT
    #   KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
    #   KAFKA_CFG_INTER_BROKER_LISTENER_NAME: PLAINTEXT_BROKER
    #   KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    #   KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    #   KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR: 1
    #   KAFKA_CFG_MIN_INSYNC_REPLICAS: 1
    # volumes:
    #   - ./kafka-data:/bitnami/kafka

#rabbit mq
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"     # Port cho giao tiếp AMQP
      - "15672:15672"   # Port cho giao diện quản lý
    environment:
      RABBITMQ_DEFAULT_USER: user   
      RABBITMQ_DEFAULT_PASS: password   